/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: a575084721fa3bfee7fd002b32e2b0e6)
// Runtime types generated with workerd@1.20251125.0 2025-10-08 global_fetch_strictly_public,nodejs_compat

/**
 * --- 1. Cloudflare 特定接口定义 ---
 * 这一部分定义了 Wrangler CLI 和 Worker 运行时提供的项目特定类型。
 */
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index"); // 声明 Worker 的主模块入口
	}
	/**
	 * Worker 运行时环境 (Env) 接口的定义，包含了通过绑定注入的资源。
	 * 这是 Worker 脚本中访问资源的类型契约。
	 */
	interface Env {
		AI: Ai; // Workers AI 绑定 (已在 wrangler.json 中配置)
		ASSETS: Fetcher; // 静态资产绑定 (已在 wrangler.json 中配置)
		// 注意：如果配置了 KV，这里会自动添加 KVNamespace 类型定义，例如：
		// CHAT_CONTEXT_KV: KVNamespace; 
	}
}
// 导出 Env 接口，使其可以在 Worker 脚本 (如 index.ts) 中被引用。
interface Env extends Cloudflare.Env {}

// Begin runtime types
// ... [省略 Apache/MIT 许可证声明] ...

/**
 * --- 2. 标准 Web/Workers 运行时 API 定义 ---
 * 这一部分定义了 Worker 运行时环境中可用的 Web 标准 API，例如：
 */

// DOMException：虽然 Worker 没有 DOM，但它是许多 Web API 错误 (如 AbortController 引起的错误) 的基类。
declare class DOMException extends Error {
// ... [省略 DOMException 属性和方法] ...
	get stack(): any;
	set stack(value: any);
}
// WorkerGlobalScopeEventMap：Worker 全局作用域支持的事件类型。
type WorkerGlobalScopeEventMap = {
	fetch: FetchEvent;           // HTTP 请求事件
	scheduled: ScheduledEvent;   // Cron 触发的定时任务事件
	queue: QueueEvent;           // Queue 消息事件
	unhandledrejection: PromiseRejectionEvent;
	rejectionhandled: PromiseRejectionEvent;
};
// WorkerGlobalScope：Worker 的全局对象接口。
declare abstract class WorkerGlobalScope extends EventTarget<WorkerGlobalScopeEventMap> {
	EventTarget: typeof EventTarget;
}
/* console：日志记录工具，输出会被 Cloudflare Logs 捕获。 */
interface Console {
// ... [省略 console 方法] ...
}
declare const console: Console;

// ... [省略 BufferSource, TypedArray, WebAssembly 相关的类型定义] ...

/**
 * ServiceWorkerGlobalScope：Worker 脚本的全局作用域。
 * 包含了所有可用的全局 API 和绑定。
 */
interface ServiceWorkerGlobalScope extends WorkerGlobalScope {
// ... [省略全局函数，如 setTimeout, fetch, self, crypto 等] ...
	/**
	 * Cloudflare：包含运行时特定的元数据和配置（如兼容性标志）。
	 */
	Cloudflare: Cloudflare; 
	// ... [省略各种 Web API 类定义，如 Headers, Request, Response, WebSocket, AbortController, URL 等] ...
}

// 全局事件监听器函数，用于处理 fetch, scheduled 等事件。
declare function addEventListener<Type extends keyof WorkerGlobalScopeEventMap>(type: Type, handler: EventListenerOrEventListenerObject<WorkerGlobalScopeEventMap[Type]>, options?: EventTargetAddEventListenerOptions | boolean): void;
// ... [省略其他全局函数] ...
declare const self: ServiceWorkerGlobalScope;
declare const crypto: Crypto;
declare const caches: CacheStorage;
declare const scheduler: Scheduler;
declare const performance: Performance;
declare const Cloudflare: Cloudflare;
declare const origin: string;
declare const navigator: Navigator;

/**
 * ExecutionContext：执行上下文接口。
 * 允许 Worker 延长生命周期，以执行异步操作（例如 KV 写入）。
 */
interface ExecutionContext<Props = unknown> {
	/**
	 * **关键方法：** 用于确保 Worker 在返回响应后继续执行给定的 Promise。
	 * 适用于异步持久化（如 KV 写入）或日志记录，以避免延迟用户响应。
	 */
	waitUntil(promise: Promise<any>): void; 
	passThroughOnException(): void;
	readonly props: Props;
}

/**
 * ExportedHandler：Worker 入口点的核心类型。
 * 定义了 Worker 可以导出的处理程序（handlers）。
 */
interface ExportedHandler<Env = unknown, QueueHandlerMessage = unknown, CfHostMetadata = unknown> {
	/**
	 * 处理 HTTP 请求的函数 (对应于您的 index.ts 中的 fetch(request, env, ctx))。
	 */
	fetch?: ExportedHandlerFetchHandler<Env, CfHostMetadata>;
	// ... [省略其他 Worker Handler 类型，如 scheduled, queue, tail] ...
}
// ... [省略其他 Web API, Durable Object, AnalyticsEngine 的类型定义] ...

/**
 * **AbortController/AbortSignal：** Cloudflare Workers 支持这些标准 Web API，
 * 这正是实现您的 **“取消生成机制”** (P0) 所依赖的技术基础。
 */
// ... [AbortController 和 AbortSignal 的类型定义位于省略部分] ...